### ISSUE TITLE
Make a sensible z-index scale on base.less

### ISSUE THREAD

**Issue by dfosco** [vtex-apps/editor#14]
*ಠ_ಠ*

**Comment by brenoc** [comment]
Inspiration: http://material-ui.com/#/components/paper

**Comment by dfosco** [comment]
@brenoc @bellacorbo I'll hit this issue maybe next week — our team conversation on CSS will touch base with this issue.

**Comment by brenoc** [comment]
alright!

**Comment by dfosco** [comment]
Added a z-index scale to [css-utils](https://github.com/vtex-apps/css-utils) and imported it into editor.

Fixed on branch `prototype/workspace-statusbar` on commit `c708e60`, will close when merged into master.

**Comment by brenoc** [comment]
@dfosco nice!

**Comment by bellacorbo** [comment]
:+1:
