### ISSUE TITLE
Show placeholder content / empty state when component is not configured

### ISSUE THREAD

**Issue by dfosco** [vtex-apps/editor#30]

**Comment by dfosco** [comment]
@bellacorbo @brenoc Let's have a conversation about these structural decisions about the editor and which ones we should move forward with — I'll leave this issue open just so we don't forget to keep up the discussion

**Comment by brenoc** [comment]
This decision is made by the developer. He may want to render something using a default settings or maybe nothing.

I think we can close this issue, since this decision does not concern the storefront-editor.
