### ISSUE TITLE
Image assets not loading on MobileSidePanel

### ISSUE THREAD

**Issue by dfosco** [vtex-apps/editor#33]
So, we're having a problem with the image assets on the MobileSidePanel. These two images, loaded according to component state, work intermittently — sometimes they do, sometimes they don't. I assume it's a problem with current instabilities in the storefront, because this didn't use to happen.

`<img src="/assets/@vtex.storefront-editor/icons/tiny-arrow.svg" alt="Abrir menu"/>`
`<img src="/assets/@vtex.storefront-editor/icons/tiny-uparrow.svg" alt="Fechar menu"/>`

Another weird problem is the avatar image which won't load _at all_ for some reason, even though it's referenced in the same manner and has an identical folder structure:

`<img src="/assets/@vtex.storefront-editor/images/brenoc.jpg" alt="" className="header-thumb"/>`

---

<img width="317" alt="screen shot 2015-10-28 at 10 32 03 pm" src="https://cloud.githubusercontent.com/assets/3229933/10807158/c470d8b0-7dc3-11e5-939d-71739e888368.png">

<img width="319" alt="screen shot 2015-10-28 at 10 28 57 pm" src="https://cloud.githubusercontent.com/assets/3229933/10807126/67668cdc-7dc3-11e5-9729-a3749319fad9.png">

**Comment by brenoc** [comment]
cc @amoreira

**Comment by dfosco** [comment]
@amoreira This is not currently a pressing issue because the layout changed and there are no more images — but referencing image assets has been a pain from the beginning developing for storefront.

Andy, can you let me know when you're able to take a look at this? That way we can test it together to make sure it's running smoothly once it's fixed. Thanks!

**Comment by dfosco** [comment]
Deprecated.
