### ISSUE TITLE
DesktopContainer is not able to render App

### ISSUE THREAD

**Issue by dfosco** [vtex-apps/editor#53]
There's a variable in *AppEditor/index.js* that toggles rendering between `DesktopContainer` and `MobileContainer`, but the desktop view is not able to load the App.

Console shows no errors either :grin:

**Comment by brenoc** [comment]
@dfosco I commented it out some time ago https://github.com/vtex-apps/editor/blob/master/src/editors/AppEditor/index.js#L3

**Comment by dfosco** [comment]
@brenoc Yep, I know — doesn't work after uncommenting it :confused:
