### ISSUE TITLE
Publish new version to upload latest style hotfix

### ISSUE THREAD

**Issue by dfosco** [vtex-apps/editor#65]
@tamorim @brenoc Could you publish a new version of the editor to the gallery? I did a hotfix to a style on `.AppContainer__inner` to fix the store's footer that was non-sticky.

thanks!

**Comment by tamorim** [comment]
@dfosco done at 861bbe809a5afb8e24d0eb87011a88fb1de0d3cd :smiley:

**Comment by dfosco** [comment]
:wink:
